#!/bin/bash -e
#Download the app here
echo MY_VARIABLE is $MY_VARIABLE
currDir=`pwd`
echo $currDir
echo $currDir/tmp
rm -rf $currDir/tmp
mkdir $currDir/tmp
cd `mktemp -d $currDir/tmp/temp_dir.XXXXXXX`
PATH=$currDir/../../../gt
echo PATH $PATH
GITHUB_TOKEN=`cat $currDir/../../../gt`
git clone git@github.com:wix-private/mre-demo-module-4.git -H "Authorization: Bearer ${GITHUB_TOKEN}" #$RepoPath
cd mre-demo-module-4
#TODO Download the installable app
npm install --legacy-peer-deps #TODO Support also JDH
npm run test